# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.4
loader_version=0.16.14
kotlin_loader_version=1.13.4+kotlin.2.2.0
# Mod Properties
mod_version=v1.0.0+1.21.7-SNAPSHOT
maven_group=com.zephbyte
archives_base_name=StreamerTag
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.128.2+1.21.7

# Night Config
night_config_version=3.8.1
# Placeholder API
placeholder_api_version=2.7.1+1.21.6